### ISSUE TITLE
Custom logo

### ISSUE THREAD

**Issue by DzSom02** [useblocks/groundwork-sphinx-theme#6]
It is not possible to add a custom logo on the theme.

**Comment by danwos** [comment]
What have you tried? 

The theme is used in a couple of projects.
For example: https://groundwork-users.readthedocs.io/en/latest/

And the logo is set in the conf.py file:
https://github.com/useblocks/groundwork-users/blob/master/docs/conf.py#L146

But I haven't tested it with the latest sphinx version.

**Comment by DzSom02** [comment]
Hi, 

Sorry my bad! 

I was trying to set the logo on the theme options instead of the conf.py

Thanks for the help!
