### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by Dr-Ari-Gami** [useblocks/groundwork-sphinx-theme#7]
This might just be me, but I tend to view a lot of documentation on my phone. I think mobile support for this theme would be awesome.

**Comment by danwos** [comment]
Looks quite good on my phone.
Some minor style problems with embedded code, but not much.

What is not working for you?

![Screenshot_20200113-051534_Chrome](https://user-images.githubusercontent.com/998700/72232840-f8f63000-35c3-11ea-806d-6a738c916ae5.jpg)

**Comment by Dr-Ari-Gami** [comment]
Sphinx didn't set a viewport. That's why I was having issues.
